(()=>{"use strict";
const KEY="ai-project-education.level1.simple-chatbot.v2",STAGES=["자료와 질문","응답 카드","MVP 실행"];
const guided=()=>({name:"진로 고민을 돕는 소크라테스",user:"진로를 고민하는 중학생·고등학생",topic:"진로에 대한 고민이 많은 학생들의 고민을 해결해주는 철학자 대화봇",scope:"학생이 자신의 관심·가치·강점·선택 기준을 질문으로 정리하도록 돕는다. 특정 직업·학과·입시를 대신 결정하거나 합격·취업을 보장하지 않는다. 심리치료·위기 상담과 출처 없는 전망은 답하지 않는다.",sources:"진로정보망 커리어넷 | 교육부 지원·한국직업능력연구원 | https://www.career.go.kr/cloud/w/main/home | 직업·학과·진로 탐색\n고용24 | 고용노동부·한국고용정보원 | https://www.work24.go.kr/cm/main.do?mid=1 | 직업·진로 정보\nSocrates, Stanford Encyclopedia of Philosophy | Stanford University | https://plato.stanford.edu/entries/socrates/ | 질문 중심 대화 방식 참고",cards:[{keywords:"좋아하는,잘하는,강점,관심",answer:"진로를 바로 정하기보다 ‘좋아하는 활동’, ‘시간이 빨리 가는 활동’, ‘다른 사람이 도움을 요청하는 일’을 나누어 적어 보세요. 세 가지가 겹치는 부분이 탐색의 출발점이 됩니다.",followup:"최근 한 달 동안 즐겁거나 뿌듯했던 활동 하나는 무엇이었나요?"},{keywords:"부모님,원하는,반대,기대,다르",answer:"부모님의 기대와 내 관심이 다를 수 있습니다. 먼저 어느 선택이 옳은지 결론내리기보다, 부모님이 중요하게 생각하는 조건과 내가 중요하게 생각하는 조건을 각각 적어 비교해 보세요.",followup:"부모님이 걱정하는 점 한 가지와 내가 포기하기 어려운 점 한 가지는 무엇인가요?"},{keywords:"모르겠,못 정,막막,지금",answer:"아직 진로를 정하지 못한 것은 실패가 아닙니다. 지금은 직업을 하나 고르는 단계보다 관심 분야를 두세 개로 넓게 탐색하는 단계일 수 있습니다.",followup:"이번 주에 직업·학과 정보 하나를 찾아보고 싶은 분야는 무엇인가요?"}]});
const blank=()=>({name:"나의 자료 기반 챗봇",user:"",topic:"",scope:"",sources:"",cards:[{keywords:"",answer:"",followup:""}]});
let state={mode:"guided",stage:0,guided:guided(),personal:blank()};const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],clean=v=>String(v??"").trim(),active=()=>state[state.mode];
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)state={...state,...saved,guided:{...guided(),...saved.guided},personal:{...blank(),...saved.personal}}}catch(_){}}function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$("#saveStatus").textContent="이 브라우저에 자동 저장됨"}catch(_){$("#saveStatus").textContent="브라우저 저장을 사용할 수 없음"}}
function researchPrompt(){const d=active();return[`다음 자료 기반 단일 HTML 챗봇을 위한 응답 카드를 만들어라. 인터넷 검색·API 기능은 넣지 말고, 제공한 자료에 없는 사실은 만들지 마라.`,`주제: ${clean(d.topic)||"미입력"}`,`사용자: ${clean(d.user)||"미입력"}`,`답변 범위: ${clean(d.scope)||"미입력"}`,`자료: ${clean(d.sources)||"미입력"}`,"","질문 유형 3~5개마다 다음 형식으로 답하라.","키워드: 쉼표로 구분","답변: 2~3문장","다음 질문: 1문장","자료 근거: 자료명"].join("\n")}
function buildPrompt(){const d=active();return[`다음 데이터를 사용해 외부 라이브러리·API·서버 없이 브라우저에서 실행되는 단일 HTML 자료 기반 챗봇을 만들어라. HTML, CSS, JavaScript 전체만 출력하라.`,`챗봇 이름: ${clean(d.name)||"나의 챗봇"}`,`사용자: ${clean(d.user)||"미입력"}`,`주제: ${clean(d.topic)||"미입력"}`,`범위: ${clean(d.scope)||"미입력"}`,`자료: ${clean(d.sources)||"미입력"}`,"응답 카드:",...d.cards.map((c,i)=>`${i+1}. 키워드: ${c.keywords}\n답변: ${c.answer}\n다음 질문: ${c.followup}`),"","필수: 질문의 키워드와 응답 카드를 연결하고, 일치 카드가 없으면 자료 범위를 밝히고 탐색 질문을 하라. 답을 꾸며내지 마라."].join("\n")}
function message(box,type,label,text){const el=document.createElement("div"),title=document.createElement("strong"),body=document.createElement("span");el.className=`chat-message ${type}`;title.textContent=label;body.textContent=text;el.append(title,body);box.append(el)}
function findCard(question){const q=question.toLowerCase();return active().cards.map(card=>({card,score:clean(card.keywords).split(/[\s,\/]+/).filter(Boolean).reduce((n,k)=>n+(q.includes(k.toLowerCase())?1:0),0)})).sort((a,b)=>b.score-a.score)[0]}
function sendQuestion(){const input=$("#mvpQuestion"),question=clean(input.value);if(!question)return;const box=$("#mvpChat"),hit=findCard(question),d=active();if(box.querySelector(".chat-empty"))box.replaceChildren();message(box,"user","사용자",question);if(hit?.score>0&&clean(hit.card.answer))message(box,"bot",d.name||"챗봇",`${hit.card.answer}\n\n${hit.card.followup||"이 주제에서 더 확인하고 싶은 점은 무엇인가요?"}`);else message(box,"bot",d.name||"챗봇",`이 질문은 현재 자료 카드에서 확실한 답을 찾지 못했습니다. ${clean(d.scope)||"제공한 자료의 범위"} 안에서 탐색할 수 있도록, 관심 있는 분야나 확인하고 싶은 조건을 한 가지 말해 줄래요?`);input.value="";input.focus()}
function renderCards(){const box=$("#cardsEditor"),d=active();box.replaceChildren();d.cards.forEach((card,index)=>{const wrap=document.createElement("section");wrap.className="card-editor";wrap.innerHTML=`<h3>응답 카드 ${index+1}</h3><label>질문 키워드<input data-card="${index}" data-key="keywords" placeholder="예: 부모님, 반대, 기대"></label><label>답변<textarea data-card="${index}" data-key="answer" rows="3" placeholder="자료를 바탕으로 한 답변"></textarea></label><label>다음 질문<textarea data-card="${index}" data-key="followup" rows="2" placeholder="생각을 이어 갈 질문"></textarea></label><button class="secondary remove-card" data-remove="${index}" type="button">이 카드 삭제</button>`;box.append(wrap);[...wrap.querySelectorAll("[data-key]")].forEach(input=>{input.value=card[input.dataset.key];input.oninput=()=>{d.cards[index][input.dataset.key]=input.value;save();renderPreview()}});wrap.querySelector(".remove-card").onclick=()=>{if(d.cards.length===1){d.cards[0]={keywords:"",answer:"",followup:""}}else d.cards.splice(index,1);save();renderCards();renderPreview()}})}
function renderPreview(){const d=active();$("#botNamePreview").textContent=clean(d.name)||"나의 자료 기반 챗봇";$("#topicPreview").textContent=clean(d.topic)||"아직 정하지 않음";$("#cardCountPreview").textContent=`${d.cards.filter(card=>clean(card.answer)).length}개`;$("#modePreview").textContent=state.mode==="guided"?"따라하기 실습":"빈 개인 실습";$("#researchPrompt").textContent=researchPrompt();$("#buildPrompt").textContent=buildPrompt()}
function renderStage(){all(".step-panel").forEach(panel=>panel.classList.toggle("active",Number(panel.dataset.step)===state.stage));all("[data-progress]").forEach(item=>{const i=Number(item.dataset.progress);item.classList.toggle("active",i===state.stage);item.classList.toggle("done",i<state.stage)});$("#prevStage").disabled=state.stage===0;$("#nextStage").disabled=state.stage===2;$("#stageStatus").textContent=`${state.stage+1} / 3 · ${STAGES[state.stage]}`;renderPreview();renderCards()}
function bind(){["name","user","topic","scope","sources"].forEach(key=>{const input=$(`[data-bind="${key}"]`);input.oninput=()=>{active()[key]=input.value;save();renderPreview()}})}
function renderInputs(){["name","user","topic","scope","sources"].forEach(key=>$(`[data-bind="${key}"]`).value=active()[key]);renderStage()}
function setMode(mode){state.mode=mode;state.stage=0;save();renderInputs()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function standaloneHtml(){const d=active(),data=JSON.stringify({name:d.name,scope:d.scope,cards:d.cards}).replace(/</g,"\\u003c");return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(d.name||"자료 기반 챗봇")}</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:30px auto;padding:0 16px;background:#f2f8f4;color:#18302a}#chat{min-height:300px;padding:14px;border-radius:12px;background:#14232d;color:#fff}.m{max-width:85%;margin:8px 0;padding:10px;border-radius:10px;white-space:pre-wrap}.u{margin-left:auto;background:#dceef8;color:#152b37}.b{background:#263c48}input,button{padding:10px;font:inherit}input{width:72%}button{width:25%;background:#17795a;color:#fff;border:0;border-radius:8px}</style><h1>${escapeHtml(d.name||"자료 기반 챗봇")}</h1><p>${escapeHtml(d.topic||"")}</p><div id="chat">질문을 입력해 보세요.</div><p><input id="q" placeholder="질문을 입력하세요"><button onclick="go()">보내기</button></p><script>const D=${data};function add(c,t){const e=document.createElement('div');e.className='m '+c;e.textContent=t;chat.append(e)}function go(){const q=document.querySelector('#q'),v=q.value.trim();if(!v)return;add('u',v);const h=D.cards.map(c=>({c,s:(c.keywords||'').split(/[\\s,\\/]+/).filter(Boolean).filter(k=>v.toLowerCase().includes(k.toLowerCase())).length})).sort((a,b)=>b.s-a.s)[0];add('b',h&&h.s&&h.c.answer?h.c.answer+'\\n\\n'+(h.c.followup||''): '현재 자료 카드에서 확실한 답을 찾지 못했습니다. '+(D.scope||'제공한 자료')+' 안에서 확인할 수 있는 조건을 말해 주세요.');q.value=''}<\/script>`}
function downloadHtml(){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([standaloneHtml()],{type:"text/html;charset=utf-8"}));a.href=url;a.download="my-data-based-chatbot.html";a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}function copy(text,button,label){navigator.clipboard.writeText(text).then(()=>{button.textContent="복사됨";setTimeout(()=>button.textContent=label,1200)})}
$("#guidedMode").onclick=()=>setMode("guided");$("#personalMode").onclick=()=>setMode("personal");$("#copyResearchPrompt").onclick=()=>copy(researchPrompt(),$("#copyResearchPrompt"),"자료 기반 응답 카드 프롬프트 복사");$("#copyBuildPrompt").onclick=()=>copy(buildPrompt(),$("#copyBuildPrompt"),"AI에게 더 풍부한 HTML 챗봇 만들기 요청");$("#addCard").onclick=()=>{active().cards.push({keywords:"",answer:"",followup:""});save();renderCards();renderPreview()};$("#sendMvpQuestion").onclick=sendQuestion;$("#mvpQuestion").onkeydown=e=>{if(e.key==="Enter")sendQuestion()};$("#downloadHtml").onclick=downloadHtml;$("#prevStage").onclick=()=>{if(state.stage>0){state.stage--;save();renderStage()}};$("#nextStage").onclick=()=>{if(state.stage<2){state.stage++;save();renderStage()}};
load();bind();renderInputs();
})();
