(()=>{
"use strict";
const KEY="ai-project-education.level1.chat-agent.v4";
const TEST_MODE=true;
const STAGES=["시작 판단","대화 규칙","프롬프트","검증·완성"];
const initial=()=>({stage:0,topicFit:"",expectedQuestions:"",responseScope:"",sourceRecords:"",feasibilityAiResponse:"",feasibilityDecision:"",feasibilityReason:"",name:"",user:"",role:"",sources:"",topics:"",boundaries:"",previewQuestion:"",testQuestion:"",testResponse:"",testFinding:"",reviews:{0:{decision:"",aiAdvice:"",reason:"",returnStage:0},1:{decision:"",aiAdvice:"",reason:"",returnStage:1},2:{decision:"",aiAdvice:"",reason:"",returnStage:1},3:{decision:"",aiAdvice:"",reason:"",returnStage:1}},revisionHistory:[],validationVersions:[],checks:{chatSuitable:false,boundedResponse:false,reliableSources:false,sourceUsable:false,stayedInRole:false,usedSources:false,askedAgain:false}});
let state=initial();
const $=s=>document.querySelector(s);const all=s=>[...document.querySelectorAll(s)];const clean=v=>String(v??"").trim();
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)state={...initial(),...saved,reviews:{...initial().reviews,...saved.reviews},checks:{...initial().checks,...saved.checks},revisionHistory:Array.isArray(saved.revisionHistory)?saved.revisionHistory:[],validationVersions:Array.isArray(saved.validationVersions)?saved.validationVersions:[]}}catch(_){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$("#saveStatus").textContent="이 브라우저에 자동 저장됨"}catch(_){$("#saveStatus").textContent="브라우저 저장을 사용할 수 없음"}}
function feasibilityPrompt(){return[`다음 주제가 API·검색·문서 업로드 없이, 제공된 소수의 신뢰 자료를 수동으로 프롬프트에 넣어 운영하는 교육용 대화봇으로 적합한지 냉정하게 판단하라.`,`주제와 사용 상황: ${clean(state.topicFit)||"미입력"}`,`예상 질문: ${clean(state.expectedQuestions)||"미입력"}`,`답변 범위: ${clean(state.responseScope)||"미입력"}`,`확보한 자료: ${clean(state.sourceRecords)||"미입력"}`,"","다음 형식으로 답하라.","1. 대화봇 주제 적합성: 적합 / 보완 필요 / 부적합과 이유", "2. 반복 질문과 답변 범위가 충분히 좁은지", "3. 자료의 신뢰도·최신성·사용 조건에서 확인할 점", "4. 자료가 부족하다면 찾을 자료의 작성 주체·자료 유형·확인 방법", "5. 위험: 출처 꾸며내기, 범위 초과 답변, 민감한 조언 여부", "6. 최종 판단: READY / REVISE / NOT_SUITABLE", "AI 판단은 참고이며, 실제 자료의 원문·날짜·사용 조건은 사람이 확인해야 한다."].join("\n")}
function feasibilityMissing(){const missing=[];if(!clean(state.topicFit))missing.push("대화 주제와 사용 상황");if(!clean(state.expectedQuestions))missing.push("예상 질문");if(!clean(state.responseScope))missing.push("답변 범위");if(!clean(state.sourceRecords))missing.push("자료 목록");if(!clean(state.feasibilityAiResponse))missing.push("AI 판단 결과");if(state.feasibilityDecision!=="ready")missing.push(state.feasibilityDecision?"주제·범위·자료 보완 또는 새 주제 선택":"학습자의 최종 판단");if(!clean(state.feasibilityReason))missing.push("적합 판단 이유");[["chatSuitable","대화 주제 적합성"],["boundedResponse","답변 범위 구분"],["reliableSources","신뢰 자료 2건"],["sourceUsable","자료 사용 조건"]].forEach(([key,label])=>{if(!state.checks[key])missing.push(label)});return missing}
function defineMissing(){return[["name","대화봇 이름"],["user","대상 사용자"],["role","대화 역할"],["sources","근거·자료 범위"],["topics","답변 주제"],["boundaries","금지·재질문 규칙"]].filter(([key])=>!clean(state[key])).map(([,label])=>label)}
function testMissing(){const missing=[];[["testQuestion","시험 질문"],["testResponse","실제 응답 요약"],["testFinding","발견한 문제 또는 수정 규칙"]].forEach(([key,label])=>{if(!clean(state[key]))missing.push(label)});[["stayedInRole","역할·주제 준수"],["usedSources","출처 꾸며내지 않음"],["askedAgain","재질문·답변 범위 표시"]].forEach(([key,label])=>{if(!state.checks[key])missing.push(label)});return missing}
function gateMessage(){if(state.stage===0)return feasibilityMissing();if(state.stage===1)return defineMissing();if(state.stage===3)return testMissing();return[]}
function prompt(){return[`너는 '${clean(state.name)||"대화봇"}'이다.`,`사용자: ${clean(state.user)||"아직 정하지 않음"}`,`대화 주제와 사용 상황: ${clean(state.topicFit)}`,`예상 질문: ${clean(state.expectedQuestions)}`,`역할: ${clean(state.role)||"아직 정하지 않음"}`,`답변 근거·자료 범위: ${clean(state.sources)||"아직 정하지 않음"}`,`확보한 자료 목록: ${clean(state.sourceRecords)}`,`답변할 수 있는 범위: ${clean(state.responseScope)}`,`답변 주제: ${clean(state.topics)||"아직 정하지 않음"}`,`금지·재질문 규칙: ${clean(state.boundaries)||"아직 정하지 않음"}`,"","제공된 자료와 범위를 벗어난 사실·인용·출처를 만들지 마라. 근거가 부족하면 모른다고 말하고, 필요한 정보를 짧게 재질문하라.","자료를 실제로 검색하거나 찾았다고 말하지 마라. 답변은 대화 상대의 말투를 쓰되, 사용자가 스스로 생각할 수 있는 질문을 하나 포함하라."].join("\n")}
function chatMessage(container,type,label,text){const message=document.createElement("div");message.className=`chat-message ${type}`;const title=document.createElement("strong");title.textContent=label;const body=document.createElement("span");body.textContent=text;message.append(title,body);container.append(message)}
function renderMvpPreview(){const box=$("#previewChat"),question=clean(state.previewQuestion);box.replaceChildren();if(!question){box.innerHTML='<p class="chat-empty">질문을 입력하면 규칙 기반 MVP 응답을 보여줍니다.</p>';return}chatMessage(box,"user","사용자",question);const role=clean(state.role)||"아직 정하지 않은 역할";const scope=clean(state.topics)||clean(state.responseScope)||"설정한 답변 범위";const sources=clean(state.sources)||clean(state.sourceRecords)||"학습자가 제공한 자료";const boundary=clean(state.boundaries)||"근거가 부족하면 모른다고 말하고 재질문";chatMessage(box,"bot",`${clean(state.name)||"대화봇"} · 규칙 기반 미리보기`,`${role} 설정에 따라 답변을 준비합니다.\n\n이 질문은 ‘${scope}’ 범위에서 다룹니다. 확인할 근거: ${sources}.\n\n실제 AI 답변이 아니라 규칙 표시용 MVP입니다. 실제 대화에서는 ${boundary} 원칙을 적용합니다.`)}
function renderValidationPreview(){const box=$("#validationChat"),question=clean(state.testQuestion),response=clean(state.testResponse);box.replaceChildren();if(!question&&!response){box.innerHTML='<p class="chat-empty">시험 질문과 실제 응답을 기록하면 여기에 표시됩니다.</p>';return}if(question)chatMessage(box,"user","시험 질문",question);if(response)chatMessage(box,"bot","외부 AI의 실제 응답 기록",response);else chatMessage(box,"bot","외부 AI의 실제 응답 기록","아직 기록하지 않았습니다. 외부 AI에서 실제로 시험한 뒤 응답을 붙여 넣으세요.")}
function currentReview(){return{...initial().reviews[state.stage],...(state.reviews[state.stage]||{})}}
function revisionTargets(){return state.stage<2?[[state.stage,`${state.stage+1}단계 현재 입력 수정`]]:[[1,"2단계 대화 규칙 수정"],[2,"3단계 프롬프트·MVP 다시 확인"]]}
function improvementPrompt(){const evidence=state.stage===0?`주제·사용 상황: ${clean(state.topicFit)||"미입력"}\n예상 질문: ${clean(state.expectedQuestions)||"미입력"}\n답변 범위: ${clean(state.responseScope)||"미입력"}\n자료 목록: ${clean(state.sourceRecords)||"미입력"}\n기존 AI 판단: ${clean(state.feasibilityAiResponse)||"미입력"}`:state.stage===1?`대화봇 이름: ${clean(state.name)||"미입력"}\n대상 사용자: ${clean(state.user)||"미입력"}\n역할: ${clean(state.role)||"미입력"}\n근거 자료 범위: ${clean(state.sources)||"미입력"}\n답변 주제: ${clean(state.topics)||"미입력"}\n금지·재질문 규칙: ${clean(state.boundaries)||"미입력"}`:state.stage===2?`현재 대화 프롬프트:\n${prompt()}\n\nMVP 미리보기 질문: ${clean(state.previewQuestion)||"미입력"}`:`시험 질문: ${clean(state.testQuestion)||"미입력"}\n실제 외부 AI 응답: ${clean(state.testResponse)||"미입력"}\n발견한 문제: ${clean(state.testFinding)||"미입력"}`;return[`다음 LEVEL 1 대화봇 결과를 검토하고, 보완 계획만 추천하라. AI의 의견은 참고이며 자료 원문·발행일·사용 조건을 새로 꾸며내지 마라.`,`현재 단계: ${state.stage+1}. ${STAGES[state.stage]}`,"",evidence,"","다음 형식으로 간결하게 답하라.","1. 판정: 그대로 진행 / 보완 필요", "2. 보완 이유: 최대 3개", "3. 수정 항목: [수정할 위치] [현재 문제] [구체적 수정 행동] 형식으로 최대 3개", "4. 수정 뒤 확인할 질문 또는 체크 항목 1~2개", "5. 출처·범위·민감한 조언에서 주의할 점", "자료에 없는 사실이나 출처를 만들지 말고, 부족한 자료는 어떤 작성 주체의 자료를 확인해야 하는지로만 제안하라."].join("\n")}
function renderRevisionPanel(){const review=currentReview(),choices=revisionTargets(),returnStage=$("#revisionReturnStage");$("#revisionDecision").value=review.decision;$("#aiRevisionAdvice").value=review.aiAdvice;$("#revisionReason").value=review.reason;$("#improvementPrompt").textContent=improvementPrompt();returnStage.replaceChildren();choices.forEach(([value,label])=>{const option=document.createElement("option");option.value=value;option.textContent=label;returnStage.append(option)});returnStage.value=String(choices.some(([value])=>value===Number(review.returnStage))?review.returnStage:choices[0][0]);const stageName=STAGES[state.stage];$("#revisionGuide").textContent=state.stage===3?"보완 계획을 확정하면 현재 시험 기록을 v1·v2처럼 보관합니다. 그 다음 수정 위치로 이동해 수정하고 다시 검증하세요.":`${stageName} 단계의 입력은 보존됩니다. AI 제안을 참고해 내가 고칠 내용을 확정한 뒤 수정 위치로 이동하세요.`;$("#goToRevision").disabled=review.decision!=="revise";$("#revisionState").textContent=review.decision==="revise"?"보완 계획이 이력에 저장되었습니다. 다음은 ‘② 수정 위치로 이동하기’입니다. 현재 입력과 이전 기록은 남습니다.":review.decision==="ready"?"현재 단계 통과로 기록했습니다.":"1단계 AI 제안 → 2단계 보완 계획 확정 → 3단계 수정 순서로 진행하세요.";const history=$("#revisionHistory");history.replaceChildren();if(!state.revisionHistory.length){history.textContent="아직 확정한 보완 계획이 없습니다.";return}const title=document.createElement("strong");title.textContent="확정한 보완·검증 이력";const list=document.createElement("ol");state.revisionHistory.slice(-5).reverse().forEach(item=>{const row=document.createElement("li"),version=state.validationVersions.find(record=>record.version===item.validationVersion);row.textContent=`${item.label}: ${item.reason||"보완 이유 미입력"}${item.aiAdvice?` / AI 제안: ${item.aiAdvice}`:""}${version?` / 시험: ${version.question||"미입력"} / 실제 응답: ${version.response||"미입력"}`:""}`;list.append(row)});history.append(title,list)}
function saveRevision(){const review={decision:$("#revisionDecision").value,aiAdvice:clean($("#aiRevisionAdvice").value),reason:clean($("#revisionReason").value),returnStage:Number($("#revisionReturnStage").value)};state.reviews[state.stage]=review;if(review.decision==="revise"){const label=`${STAGES[state.stage]} 보완 v${state.revisionHistory.length+1}`,entry={label,reason:review.reason,aiAdvice:review.aiAdvice,stage:state.stage};if(state.stage===3){const version=state.validationVersions.length+1;state.validationVersions.push({version,question:clean(state.testQuestion),response:clean(state.testResponse),finding:clean(state.testFinding),reason:review.reason});entry.validationVersion=version}state.revisionHistory.push(entry)}save();renderRevisionPanel()}
function goToRevision(){const review=currentReview();if(review.decision!=="revise")return;state.stage=Number(review.returnStage);save();renderStage()}
function refresh(){const feasible=feasibilityMissing().length===0;$("#agentPreview").textContent=clean(state.name)||"나의 대화봇";$("#rolePreview").textContent=clean(state.role)||"아직 정하지 않음";$("#sourcePreview").textContent=clean(state.sources)||"아직 정하지 않음";$("#boundaryPreview").textContent=clean(state.boundaries)||"아직 정하지 않음";$("#feasibilityPrompt").textContent=feasibilityPrompt();$("#prompt").textContent=prompt();$("#improvementPrompt").textContent=improvementPrompt();$("#copyPrompt").disabled=!feasible&&!TEST_MODE;$("#feasibilityState").textContent=feasible?"시작 판단 완료: 대화 규칙을 설계할 수 있습니다.":`테스트 운영: 아래 항목은 다음 단계 전 확인할 권장 사항이며, 현재는 이동을 막지 않습니다. ${feasibilityMissing().join(" / ")}`}
function renderStage(){all(".step-panel").forEach(panel=>panel.classList.toggle("active",Number(panel.dataset.step)===state.stage));all("[data-progress]").forEach(item=>{const index=Number(item.dataset.progress);item.classList.toggle("active",index===state.stage);item.classList.toggle("done",index<state.stage)});$("#prevStage").disabled=state.stage===0;$("#nextStage").textContent=state.stage===3?"검증 완료":"다음 단계";$("#stageStatus").textContent=`${state.stage+1} / 4 · ${STAGES[state.stage]}`;document.title=`LEVEL 1 | ${STAGES[state.stage]}`;renderRevisionPanel()}
function bind(){Object.keys(state).filter(key=>key!=="checks"&&key!=="stage").forEach(key=>{const input=$(`[data-bind="${key}"]`);if(input){input.value=state[key];input.addEventListener(input.tagName==="SELECT"?"change":"input",()=>{state[key]=input.value;save();refresh()})}});Object.keys(state.checks).forEach(key=>{const input=$(`[data-check="${key}"]`);if(input){input.checked=state.checks[key];input.addEventListener("change",()=>{state.checks[key]=input.checked;save();refresh()})}})}
function packageMarkdown(){return`# ${clean(state.name)||"LEVEL 1 대화형 미니 에이전트"}\n\n## 시작 판단\n- 대화 주제와 사용 상황: ${clean(state.topicFit)}\n- 예상 질문: ${clean(state.expectedQuestions)}\n- 답변 범위: ${clean(state.responseScope)}\n- 자료 목록: ${clean(state.sourceRecords)}\n- AI 판단 결과: ${clean(state.feasibilityAiResponse)}\n- 학습자 최종 판단: ${clean(state.feasibilityDecision)}\n- 판단 이유: ${clean(state.feasibilityReason)}\n\n## 프로젝트\n- 사용자: ${clean(state.user)}\n- 역할: ${clean(state.role)}\n- 답변 근거·자료 범위: ${clean(state.sources)}\n- 답변 주제: ${clean(state.topics)}\n- 금지·재질문 규칙: ${clean(state.boundaries)}\n\n## 대화 프롬프트\n\`\`\`\n${prompt()}\n\`\`\`\n\n## 테스트 기록\n- 질문: ${clean(state.testQuestion)}\n- 실제 응답 요약: ${clean(state.testResponse)}\n- 발견한 문제·수정할 규칙: ${clean(state.testFinding)}\n- 역할·주제 준수: ${state.checks.stayedInRole}\n- 출처 꾸며내지 않음: ${state.checks.usedSources}\n- 재질문·답변 범위 표시: ${state.checks.askedAgain}\n\n## 알려진 제한\n- 이 패키지는 외부 채팅 AI에 수동으로 붙여 넣어 사용한다.\n- 실제 문서 검색, 출처 자동 연결, 파일 업로드, API 호출은 포함하지 않는다.\n- AI 응답은 사람이 근거와 규칙 준수 여부를 검토한다.\n`}
function copyText(text,button,label){navigator.clipboard.writeText(text).then(()=>{button.textContent="복사됨";setTimeout(()=>button.textContent=label,1200)}).catch(()=>alert("복사할 수 없습니다. 코드 영역을 직접 선택해 복사하세요."))}
function download(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([packageMarkdown()],{type:"text/markdown;charset=utf-8"}));a.download="level-1-chat-agent-package.md";document.body.append(a);a.click();const url=a.href;a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
$("#copyFeasibilityPrompt").onclick=()=>copyText(feasibilityPrompt(),$("#copyFeasibilityPrompt"),"적합성 판단 프롬프트 복사");$("#copyPrompt").onclick=()=>copyText(prompt(),$("#copyPrompt"),"프롬프트 복사");$("#copyImprovementPrompt").onclick=()=>copyText(improvementPrompt(),$("#copyImprovementPrompt"),"보완 계획 요청 프롬프트 복사");$("#downloadPackage").onclick=download;
$("#runPreview").onclick=renderMvpPreview;$("#showValidationPreview").onclick=renderValidationPreview;
$("#saveRevision").onclick=saveRevision;$("#goToRevision").onclick=goToRevision;
$("#prevStage").onclick=()=>{if(state.stage>0){state.stage--;save();renderStage()}};$("#nextStage").onclick=()=>{const missing=gateMessage();if(!TEST_MODE&&missing.length){alert(`이 단계에서 확인할 항목: ${missing.join(" / ")}`);return}if(state.stage===3){alert("검증 기록이 완성되었습니다. 대화봇 패키지를 내려받으세요.");return}state.stage++;save();renderStage()};
load();bind();refresh();renderMvpPreview();renderValidationPreview();renderStage();
})();
