(()=>{
"use strict";
const D=window.LEVEL1_DATA;
const params=new URLSearchParams(location.search);
const audience=["elementary","secondary","adult"].includes(params.get("audience"))?params.get("audience"):"elementary";
const profile=D.audienceExamples[audience];
const KEY=`ai-project-education.level1.v3.${audience}`;
const stages=[
  {name:"1. 목표",title:"무엇을 도와주는 에이전트인가?",web:"샘플을 참고해 사용자·상황·문제·성공 결과를 적습니다.",ai:"작성한 목표가 너무 넓거나 모호하지 않은지 AI에게 점검받습니다."},
  {name:"2. 판단정보",title:"무엇을 보고 판단해야 하는가?",web:"에이전트가 판단할 때 반드시 확인해야 할 사실·조건·규칙 3개를 적습니다.",ai:"빠진 판단 기준이 있는지 AI에게 확인합니다."},
  {name:"3. 작동순서",title:"어떤 순서로 처리할 것인가?",web:"필수 입력과 처리 순서 4개, 최종 출력 모습을 정합니다.",ai:"순서가 겹치거나 빠진 부분이 있는지 AI에게 검토받습니다."},
  {name:"4. 에이전트 생성",title:"실제로 사용할 에이전트 지침 만들기",web:"앞에서 적은 내용을 자동으로 조립한 에이전트 카드를 확인합니다.",ai:"완성된 지침을 복사해 생성형 AI에 붙여넣고 실제 에이전트처럼 사용합니다."},
  {name:"5. AI 테스트",title:"정상·애매·실패 상황에서 시험하기",web:"3가지 테스트 입력과 실제 AI의 답을 기록합니다.",ai:"각 테스트 입력을 에이전트 지침과 함께 AI에 보내 작동 결과를 확인합니다."},
  {name:"6. 완성",title:"복사해서 다시 쓸 수 있는 완성본 만들기",web:"테스트에서 고칠 점 하나를 반영하고 최종 패키지를 확인합니다.",ai:"최종 에이전트 지침을 복사해 새 채팅에서도 그대로 사용할 수 있는지 확인합니다."}
];
const $=s=>document.querySelector(s);
const all=s=>[...document.querySelectorAll(s)];
const clean=v=>String(v??"").trim();
function initial(){return{audience,stage:0,goal:{user:"",scene:"",problem:"",success:""},criteria:["","",""],flow:{required:"",steps:["","","",""],output:""},tests:{normal:{input:"",result:""},edge:{input:"",result:""},fail:{input:"",result:""}},improve:"",updatedAt:new Date().toISOString()}}
let state=initial();
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);state={...initial(),...saved,goal:{...initial().goal,...saved.goal},flow:{...initial().flow,...saved.flow,steps:Array.isArray(saved.flow?.steps)?saved.flow.steps.slice(0,4):["","","",""]},tests:{...initial().tests,...saved.tests}}}}catch(_){}}
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));$("#saveStatus").textContent="자동 저장됨"}catch(_){$("#saveStatus").textContent="저장 사용 불가"}}
function sampleGoal(){return profile.define}
function sampleCriteria(){if(audience==="elementary")return["현재 용돈과 사고 싶은 물건의 가격","다음 용돈일까지 꼭 필요한 지출","구매 후 남는 돈이 너무 적지 않은지"];
if(audience==="secondary")return["시험 날짜와 과목별 남은 범위","하루 실제 공부 가능 시간","취약 과목과 반드시 해야 할 일정"];
return["여행 날짜·인원·총예산","숙소 위치·교통수단·하루 이동 한도","선호 활동과 예약·운영시간 조건"]}
function sampleRequired(){if(audience==="elementary")return"현재 용돈, 물건 가격, 다음 용돈일까지 남은 날, 필수 지출";if(audience==="secondary")return"시험 날짜, 과목, 범위, 하루 공부 가능 시간, 취약 과목, 고정 일정";return"여행 날짜, 인원, 예산, 숙소, 교통수단, 취향, 체력·예약 조건"}
function sampleTests(){if(audience==="elementary")return{normal:"용돈 32,000원 / 가격 18,000원 / 필수지출 8,000원",edge:"가격이 용돈의 대부분이지만 다음 용돈이 내일 들어옴",fail:"현재 용돈이나 물건 가격을 알려주지 않음"};if(audience==="secondary")return{normal:"시험 D-10 / 6과목 / 평일 2시간 / 수학 취약",edge:"시험은 D-3인데 하루 공부 가능 시간이 1시간뿐",fail:"시험 날짜와 과목 범위를 알려주지 않음"};return{normal:"3박4일 / 가족3명 / 180만원 / 렌터카 없음",edge:"가고 싶은 곳이 많지만 하루 이동 시간이 5시간 이상",fail:"여행 날짜나 예산을 알려주지 않음"}}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function agentText(){const g=state.goal,c=state.criteria.map(clean).filter(Boolean),steps=state.flow.steps.map(clean).filter(Boolean);return[`# ${profile.name} 에이전트`,``, `## 역할`,`${clean(g.user)||"(사용자)"}가 ${clean(g.scene)||"(상황)"}에서 ${clean(g.problem)||"(문제)"}를 해결하도록 돕는다.`,``,`## 성공 결과`,clean(g.success)||"(성공 결과 미정)",``,`## 반드시 확인할 정보·기준`,...(c.length?c.map((x,i)=>`${i+1}. ${x}`):["(미정)"]),``,`## 사용자에게 받을 입력`,clean(state.flow.required)||"(미정)",``,`## 처리 순서`,...(steps.length?steps.map((x,i)=>`${i+1}. ${x}`):["(미정)"]),``,`## 출력 형식`,clean(state.flow.output)||profile.outputFormat,``,`## 안전 규칙`,`- 필수 정보가 부족하면 추측하지 말고 다시 질문한다.`,`- 계산·날짜·예산 등은 입력값을 다시 확인한다.`,`- 확실하지 않은 외부 정보는 사실처럼 단정하지 않는다.`].join("\n")}
function finalPackage(){return[`# LEVEL 1 미니 에이전트 완성본`,``,`대상: ${profile.audience}`,`예시: ${profile.name}`,``,`## 에이전트 지침`,agentText(),``,`## 테스트 기록`,`### 정상`,`입력: ${clean(state.tests.normal.input)}`,`결과: ${clean(state.tests.normal.result)}`,``,`### 애매`,`입력: ${clean(state.tests.edge.input)}`,`결과: ${clean(state.tests.edge.result)}`,``,`### 실패`,`입력: ${clean(state.tests.fail.input)}`,`결과: ${clean(state.tests.fail.result)}`,``,`## 마지막 개선`,clean(state.improve)||"(아직 기록 없음)"].join("\n")}
function aiPrompt(){const s=state.stage;if(s===0)return`다음 미니 에이전트 목표가 너무 넓거나 모호한지 점검해 줘. 고칠 부분만 3개 이내로 알려줘.\n\n사용자: ${clean(state.goal.user)}\n상황: ${clean(state.goal.scene)}\n문제: ${clean(state.goal.problem)}\n성공 결과: ${clean(state.goal.success)}`;
if(s===1)return`다음 에이전트가 판단하려면 어떤 정보나 기준이 빠졌는지 확인해 줘. 꼭 필요한 것만 제안해 줘.\n\n목표: ${clean(state.goal.problem)}\n현재 기준:\n${state.criteria.map((x,i)=>`${i+1}. ${clean(x)}`).join("\n")}`;
if(s===2)return`다음 에이전트 처리 순서가 실제로 실행 가능한지 검토해 줘. 겹치거나 빠진 단계만 지적해 줘.\n\n필수 입력: ${clean(state.flow.required)}\n처리 순서:\n${state.flow.steps.map((x,i)=>`${i+1}. ${clean(x)}`).join("\n")}\n출력: ${clean(state.flow.output)}`;
if(s===3)return agentText();
if(s===4){const t=state.tests.normal;return`${agentText()}\n\n---\n아래 입력으로 테스트해 줘. 부족한 정보가 있으면 추측하지 말고 먼저 질문해.\n${clean(t.input)}`}
return agentText()}
function complete(s){if(s===0)return["user","scene","problem","success"].every(k=>clean(state.goal[k]));if(s===1)return state.criteria.every(x=>clean(x));if(s===2)return clean(state.flow.required)&&state.flow.steps.every(x=>clean(x))&&clean(state.flow.output);if(s===3)return complete(0)&&complete(1)&&complete(2);if(s===4)return Object.values(state.tests).every(t=>clean(t.input)&&clean(t.result));return complete(4)&&clean(state.improve)}
function renderProgress(){const p=$("#progress");p.innerHTML=stages.map((x,i)=>`<button type="button" data-step="${i}" class="${i===state.stage?"active":""} ${complete(i)?"done":""}">${x.name}</button>`).join("");all("[data-step]").forEach(b=>b.addEventListener("click",()=>{state.stage=+b.dataset.step;render();save()}))}
function renderHeader(){$("#audienceChip").textContent=`${profile.audience} · ${profile.name}`;$("#stageCount").textContent=`${state.stage+1} / 6`;$("#stageName").textContent=stages[state.stage].title;$("#stageHint").textContent="왼쪽 샘플을 보고 오른쪽만 작성하세요."}
function renderDemo(){const box=$("#demoBox");if(audience==="elementary"){box.innerHTML=`<div class="demo-head"><strong>용돈지킴이 미니 데모</strong><span class="demo-badge">완성 결과 미리보기</span></div><div class="demo-grid"><label>현재 용돈<input id="d1" type="number" value="32000"></label><label>물건 가격<input id="d2" type="number" value="18000"></label><label>필수 지출<input id="d3" type="number" value="8000"></label><label>다음 용돈까지<input id="d4" type="number" value="12"></label></div><div class="copy-row"><button id="runDemo" class="btn small" type="button">판단해보기</button></div><div id="demoResult" class="demo-result">버튼을 누르면 완성 에이전트가 어떤 식으로 답하는지 볼 수 있습니다.</div>`;$("#runDemo").onclick=()=>{const money=+$(`#d1`).value,price=+$(`#d2`).value,need=+$(`#d3`).value,days=+$(`#d4`).value,left=money-price-need;$("#demoResult").innerHTML=left<0?`<strong>기다리기 추천</strong><br>구매하면 필수 지출까지 감당하기 어렵습니다. 부족액 ${Math.abs(left).toLocaleString()}원.`:left<5000?`<strong>조금 더 기다리기</strong><br>구매 후 여유자금이 ${left.toLocaleString()}원뿐입니다. 다음 용돈까지 ${days}일 남았습니다.`:`<strong>구매 가능</strong><br>필수 지출을 제외하고 ${left.toLocaleString()}원이 남습니다. 더 싼 대안도 비교해 보세요.`}}
else if(audience==="secondary"){box.innerHTML=`<div class="demo-head"><strong>시험기간 플래너 미니 데모</strong><span class="demo-badge">완성 결과 미리보기</span></div><div class="demo-grid"><label>시험까지 남은 날<input id="d1" type="number" value="10"></label><label>하루 공부 가능 시간<input id="d2" type="number" value="2"></label><label>과목 수<input id="d3" type="number" value="6"></label><label>취약 과목<input id="d4" value="수학, 영어"></label></div><div class="copy-row"><button id="runDemo" class="btn small" type="button">계획 보기</button></div><div id="demoResult" class="demo-result">버튼을 누르면 계획 결과의 형태를 볼 수 있습니다.</div>`;$("#runDemo").onclick=()=>{const days=+$(`#d1`).value,h=+$(`#d2`).value,n=+$(`#d3`).value,weak=$(`#d4`).value;$("#demoResult").innerHTML=`<strong>총 ${days*h}시간 확보</strong><br>오늘 핵심: ${esc(weak||"취약 과목")} 우선 60분 → 다른 과목 40분 → 복습 20분.<br>${n}과목을 남은 ${days}일에 반복 배치합니다.`}}
else{box.innerHTML=`<div class="demo-head"><strong>여행 일정 에이전트 미니 데모</strong><span class="demo-badge">완성 결과 미리보기</span></div><div class="demo-grid"><label>여행 일수<input id="d1" type="number" value="4"></label><label>총예산(만원)<input id="d2" type="number" value="180"></label><label>인원<input id="d3" type="number" value="3"></label><label>선호 활동<input id="d4" value="수영, 맛집"></label></div><div class="copy-row"><button id="runDemo" class="btn small" type="button">일정 보기</button></div><div id="demoResult" class="demo-result">버튼을 누르면 여행 일정 결과의 형태를 볼 수 있습니다.</div>`;$("#runDemo").onclick=()=>{const days=+$(`#d1`).value,budget=+$(`#d2`).value,people=+$(`#d3`).value,pref=$(`#d4`).value;$("#demoResult").innerHTML=`<strong>${days-1}박 ${days}일 · ${people}명 · ${budget}만원</strong><br>1일차: 이동+숙소 주변 / 2일차: ${esc(pref)} 중심 핵심 일정 / 3일차: 이동 적은 보조 일정 / 마지막날: 체크아웃+귀국 동선.<br>예약 필요 항목과 우천 대안도 함께 제시합니다.`}}
}
function sampleStage(){const g=sampleGoal(),criteria=sampleCriteria(),tests=sampleTests(),s=state.stage;let html="";if(s===0)html=`<div class="sample-card"><small>사용자</small><p>${esc(g.user)}</p></div><div class="sample-card"><small>사용 장면</small><p>${esc(g.scene)}</p></div><div class="sample-card"><small>해결할 문제</small><p>${esc(g.problem)}</p></div><div class="sample-card"><small>성공 결과</small><p>${esc(g.success)}</p></div>`;if(s===1)html=criteria.map((x,i)=>`<div class="sample-card"><small>판단 기준 ${i+1}</small><p>${esc(x)}</p></div>`).join("");if(s===2)html=`<div class="sample-card"><small>필수 입력</small><p>${esc(sampleRequired())}</p></div><div class="sample-card"><small>처리 순서</small><ol>${profile.steps.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div><div class="sample-card"><small>출력</small><p>${esc(profile.outputFormat)}</p></div>`;if(s===3)html=`<div class="sample-card"><small>완성 에이전트의 핵심</small><p>역할 + 판단 기준 + 입력 + 처리 순서 + 출력 + 부족한 정보가 있을 때의 중단 규칙</p></div>`;if(s===4)html=`<div class="sample-card"><small>정상 테스트</small><p>${esc(tests.normal)}</p></div><div class="sample-card"><small>애매 테스트</small><p>${esc(tests.edge)}</p></div><div class="sample-card"><small>실패 테스트</small><p>${esc(tests.fail)}</p></div>`;if(s===5)html=`<div class="sample-card"><small>완성 기준</small><ul><li>새 채팅에 붙여넣어도 역할이 이해된다.</li><li>필수 정보가 없으면 질문한다.</li><li>결과 형식이 매번 비슷하다.</li><li>테스트에서 발견한 문제를 한 번 고쳤다.</li></ul></div>`;$("#sampleStage").innerHTML=html}
function formStage(){const s=state.stage;let html="";if(s===0)html=`<div class="form-grid"><label class="field">누가 사용할까?<textarea data-bind="goal.user" rows="3" placeholder="${esc(sampleGoal().user)}"></textarea></label><label class="field">언제 사용할까?<textarea data-bind="goal.scene" rows="3" placeholder="${esc(sampleGoal().scene)}"></textarea></label><label class="field full">무슨 문제를 해결할까?<textarea data-bind="goal.problem" rows="3" placeholder="${esc(sampleGoal().problem)}"></textarea></label><label class="field full">어떤 결과가 나오면 성공일까?<textarea data-bind="goal.success" rows="3" placeholder="${esc(sampleGoal().success)}"></textarea></label></div>`;if(s===1)html=`<div class="criteria-grid">${state.criteria.map((x,i)=>`<label class="field"><span>판단 기준 ${i+1}</span><div class="criterion-row"><span>${i+1}</span><textarea data-bind="criteria.${i}" rows="3" placeholder="${esc(sampleCriteria()[i])}"></textarea></div></label>`).join("")}</div>`;if(s===2)html=`<label class="field">사용자에게 꼭 받아야 할 입력<textarea data-bind="flow.required" rows="3" placeholder="${esc(sampleRequired())}"></textarea></label><div class="steps">${state.flow.steps.map((x,i)=>`<label class="field"><span>처리 ${i+1}</span><div class="step-row"><span>${i+1}</span><textarea data-bind="flow.steps.${i}" rows="2" placeholder="${esc(profile.steps[i]||"")}"></textarea></div></label>`).join("")}</div><label class="field">최종 출력 모습<textarea data-bind="flow.output" rows="3" placeholder="${esc(profile.outputFormat)}"></textarea></label>`;if(s===3)html=`<div class="notice">앞 단계 내용이 자동 조립됩니다. 틀린 내용이 있으면 이전 단계로 돌아가 고치세요.</div><pre id="agentPreview" class="agent-preview"></pre>`;if(s===4){const tests=sampleTests();html=`<div class="test-grid">${[["normal","정상 입력",tests.normal],["edge","애매한 입력",tests.edge],["fail","실패 입력",tests.fail]].map(([k,label,ph])=>`<div class="test-card"><h4>${label}</h4><label class="field">AI에 보낼 입력<textarea data-bind="tests.${k}.input" rows="2" placeholder="${esc(ph)}"></textarea></label><label class="field">실제 AI의 답에서 확인한 점<textarea data-bind="tests.${k}.result" rows="3" placeholder="잘된 점 또는 문제를 짧게 기록"></textarea></label></div>`).join("")}</div>`}if(s===5)html=`<label class="field">테스트 후 한 가지 개선<textarea data-bind="improve" rows="3" placeholder="예: 필수 정보가 부족할 때 추천하지 않고 먼저 질문하도록 규칙을 추가했다."></textarea></label><label class="field">완성 패키지<textarea id="finalPackage" class="final-package" readonly></textarea></label><div class="copy-row"><button id="copyFinal" class="btn" type="button">최종 에이전트 복사</button><button id="downloadFinal" class="btn secondary" type="button">패키지 .md 저장</button></div>`;$("#webForm").innerHTML=html;syncInputs();bindInputs();if(s===3)$("#agentPreview").textContent=agentText();if(s===5){$("#finalPackage").value=finalPackage();$("#copyFinal").onclick=()=>copy(agentText(),"최종 에이전트 지침을 복사했습니다.");$("#downloadFinal").onclick=download}}
function get(path){return path.split(".").reduce((o,k)=>o?.[Number.isInteger(+k)?+k:k],state)}
function set(path,v){const parts=path.split("."),last=parts.pop();let o=state;for(const p of parts)o=o[Number.isInteger(+p)?+p:p];o[Number.isInteger(+last)?+last:last]=v}
function syncInputs(){all("[data-bind]").forEach(el=>el.value=get(el.dataset.bind)??"")}
function bindInputs(){all("[data-bind]").forEach(el=>el.addEventListener("input",()=>{set(el.dataset.bind,el.value);save();renderFinish();renderProgress();if(state.stage===3)$("#agentPreview").textContent=agentText();if(state.stage===5)$("#finalPackage").value=finalPackage();renderAI()}))}
function renderAI(){$("#webHelp").textContent=stages[state.stage].web;$("#aiHelp").textContent=stages[state.stage].ai;$("#aiPrompt").textContent=aiPrompt();$("#copyAI").textContent=state.stage===3?"에이전트 지침 복사":"AI에 보낼 내용 복사"}
function renderFinish(){const ok=complete(state.stage);$("#finishState").textContent=ok?"완료 조건 충족":"아직 작성할 내용이 있습니다";$("#finishState").className=ok?"ready":"";let list=[];if(state.stage===0)list=["사용자·상황·문제·성공 결과를 모두 작성"];if(state.stage===1)list=["판단 정보·기준 3개 작성"];if(state.stage===2)list=["필수 입력 + 처리 순서 4개 + 출력 모습 작성"];if(state.stage===3)list=["앞 3단계가 완성되어 에이전트 카드가 생성됨"];if(state.stage===4)list=["정상·애매·실패 테스트의 입력과 실제 결과 기록"];if(state.stage===5)list=["테스트를 바탕으로 한 가지 개선 기록","최종 에이전트 지침 복사 후 새 채팅에서 확인"];$("#finishList").innerHTML=list.map(x=>`<li>${esc(x)}</li>`).join("")}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);toast(msg)}catch(_){const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();toast(msg)}}
function toast(msg){$("#saveStatus").textContent=msg;setTimeout(()=>$("#saveStatus").textContent="자동 저장됨",1800)}
function download(){const blob=new Blob([finalPackage()],{type:"text/markdown;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`level1-${audience}-agent.md`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){renderHeader();renderProgress();renderDemo();sampleStage();formStage();renderAI();renderFinish();$("#prev").disabled=state.stage===0;$("#next").textContent=state.stage===5?"최종 확인":"다음 단계";$("#next").disabled=false;save()}
function init(){load();$("#backIntro").href="./index.html";$("#reset").onclick=()=>{if(confirm("이 대상의 따라하기 기록을 모두 삭제할까요?")){localStorage.removeItem(KEY);state=initial();render()}};$("#copyAI").onclick=()=>copy(aiPrompt(),state.stage===3?"에이전트 지침을 복사했습니다.":"AI에 보낼 내용을 복사했습니다.");$("#prev").onclick=()=>{if(state.stage>0){state.stage--;render();scrollTo({top:0,behavior:"smooth"})}};$("#next").onclick=()=>{if(state.stage<5){state.stage++;render();scrollTo({top:0,behavior:"smooth"})}else{renderFinish();toast(complete(5)?"완성 조건을 모두 확인했습니다.":"아직 마지막 개선 기록이 필요합니다.")}};render()}
document.addEventListener("DOMContentLoaded",init);
})();