(()=>{
"use strict";
const D=window.LEVEL1_DATA,qs=new URLSearchParams(location.search),aud=["elementary","secondary","adult"].includes(qs.get("audience"))?qs.get("audience"):"elementary",profile=D.audienceExamples[aud],KEY=`ai-project-education.level1.v5.${aud}`,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],clean=v=>String(v??"").trim();
const stages=[
{name:"1. MVP 제작",title:"목표와 최소 기능으로 첫 버전을 만든다",web:"에이전트 이름, 사용자, 해결할 문제, 원하는 결과, 꼭 필요한 입력만 정합니다.",ai:"이 정보로 지금 시험할 수 있는 가장 작은 MVP 지침을 생성합니다.",check:"첫 버전의 목표와 입력·출력이 한 문장으로 설명되면 다음으로 갑니다."},
{name:"2. 수정·제약",title:"써보고 고친다. 특히 하지 말아야 할 일을 정한다",web:"MVP를 써본 뒤 고칠 점과 반드시 지킬 조건, 금지조건, 재질문 조건만 추가합니다.",ai:"기존 MVP에 제약조건과 실패 시 행동을 반영해 지침을 다시 다듬습니다.",check:"금지조건과 정보 부족 시 행동이 명확하면 다음으로 갑니다."},
{name:"3. 검증",title:"사용자 검증과 AI 검증을 나눠서 본다",web:"실제 사용자가 느낀 문제와 AI가 찾아낸 실패 가능성을 각각 기록합니다.",ai:"에이전트를 칭찬하지 말고 깨뜨리는 관점에서 모호함·충돌·정보부족을 찾아달라고 요청합니다.",check:"사용자 문제와 AI 취약점이 모두 기록되면 다음으로 갑니다."},
{name:"4. 배포 판단",title:"이제 어디까지 개발할지 결정한다",web:"로컬/웹, 공유범위, 데이터 저장, DB·외부 API 필요성을 판단합니다.",ai:"선택 조건을 바탕으로 필요한 다음 기술 수준만 추천하게 합니다.",check:"최종 목적은 ‘완성’이 아니라 다음 개발 범위와 기술 선택을 결정하는 것입니다."}
];
function init(){return{stage:0,mvp:{name:profile.name,user:"",problem:"",outcome:"",required:""},refine:{issue:"",must:"",mustNot:"",askAgain:""},validate:{userResult:"",aiResult:""},delivery:{place:"local",share:"personal",data:"none",external:"no"}}}
let state=init();
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);state={...init(),...s,mvp:{...init().mvp,...s.mvp},refine:{...init().refine,...s.refine},validate:{...init().validate,...s.validate},delivery:{...init().delivery,...s.delivery}}}}catch(_){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$("#saveStatus").textContent="자동 저장됨"}catch(_){$("#saveStatus").textContent="저장 사용 불가"}}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function splitReq(){return clean(state.mvp.required)?state.mvp.required.split(/[,/·\n]/).map(x=>x.trim()).filter(Boolean):[]}
function baseAgent(){const m=state.mvp,r=state.refine;return[`# ${clean(m.name)||profile.name}`,``,`## 역할`,`${clean(m.user)||"[사용자]"}가 ${clean(m.problem)||"[문제]"}를 해결해 ${clean(m.outcome)||"[결과]"}를 얻도록 돕는다.`,``,`## 필요한 입력`,clean(m.required)||"[필수 입력]",``,`## 기본 처리 방식`,...profile.steps.slice(0,4).map((x,i)=>`${i+1}. ${x}`),``,`## 반드시 해야 할 것`,clean(r.must)||"필수 정보와 조건을 확인한다.",``,`## 절대 하지 말아야 할 것`,clean(r.mustNot)||"정보가 부족한데 추측으로 결정하지 않는다.",``,`## 다시 질문할 조건`,clean(r.askAgain)||"필수 정보가 없거나 충돌하면 먼저 질문한다.",``,`## 출력`,profile.outputFormat].join("\n")}
function prompt(){const m=state.mvp,r=state.refine,v=state.validate,d=state.delivery;if(state.stage===0)return[`나는 ${clean(m.name)||profile.name}라는 미니 AI 에이전트를 만들고 있다.`,`다음 정보만으로 바로 시험할 수 있는 가장 작은 MVP 지침을 만들어 줘. 기능을 늘리지 마.`,``,`사용자: ${clean(m.user)}`,`해결할 문제: ${clean(m.problem)}`,`원하는 결과: ${clean(m.outcome)}`,`필수 입력: ${clean(m.required)}`,``,`역할 / 필요한 입력 / 처리 순서 / 출력 형식 / 정보 부족 시 행동 순서로 작성해 줘.`].join("\n");if(state.stage===1)return[baseAgent(),``,`--- 수정 요청 ---`,`써보니 생긴 문제: ${clean(r.issue)}`,`반드시 해야 할 것: ${clean(r.must)}`,`절대 하지 말아야 할 것: ${clean(r.mustNot)}`,`다시 질문할 조건: ${clean(r.askAgain)}`,``,`위 내용을 반영해 지침을 다시 작성해 줘. 특히 금지조건과 실패 시 행동을 분명하게 만들어 줘.`].join("\n");if(state.stage===2)return[baseAgent(),``,`--- 검증 요청 ---`,`이 에이전트를 실패시키는 관점에서 검증해 줘.`,`정보 부족 / 조건 충돌 / 무리한 요구 / 잘못된 정보 / 규칙 모호성 각각에 대해 테스트 입력, 위험, 통과 기준, 수정 제안을 짧게 제시해 줘.`,``,`현재 사용자 검증 메모: ${clean(v.userResult)||"아직 없음"}`].join("\n");return[`다음 에이전트의 배포 범위를 판단해 줘.`,``,`에이전트: ${clean(m.name)||profile.name}`,`사용 위치: ${d.place}`,`공유 범위: ${d.share}`,`저장 데이터: ${d.data}`,`외부 데이터/API: ${d.external}`,``,`로컬 유지 / 정적 웹 / 웹+DB / 외부 API 연동 중 필요한 수준만 추천하고 다음 개발 TASK 3개를 제시해 줘.`].join("\n")}
function complete(i){if(i===0)return["name","user","problem","outcome","required"].every(k=>clean(state.mvp[k]));if(i===1)return["issue","must","mustNot","askAgain"].every(k=>clean(state.refine[k]));if(i===2)return clean(state.validate.userResult)&&clean(state.validate.aiResult);return true}
function arch(){const d=state.delivery;if(d.data==="database")return"웹 + 데이터베이스";if(d.external==="yes")return"웹 + 외부 API 연동";if(d.place==="web"||d.share!=="personal")return"정적 웹 우선";return"로컬/채팅형 유지"}
function renderProgress(){$("#progress").innerHTML=stages.map((x,i)=>`<button type="button" data-step="${i}" class="${i===state.stage?"active":""} ${complete(i)?"done":""}">${x.name}</button>`).join("");all("[data-step]").forEach(b=>b.onclick=()=>{state.stage=+b.dataset.step;render();save()})}
function renderHeader(){$("#audienceChip").textContent=`${profile.audience} · ${profile.name}`;$("#stageCount").textContent=`${state.stage+1} / 4`;$("#stageName").textContent=stages[state.stage].title;$("#webHelp").textContent=stages[state.stage].web;$("#aiHelp").textContent=stages[state.stage].ai;$("#finishState").textContent=stages[state.stage].check}
function liveRules(){const r=state.refine;return`${clean(r.must)?`<div class="rule must">✓ ${esc(r.must)}</div>`:""}${clean(r.mustNot)?`<div class="rule no">금지 · ${esc(r.mustNot)}</div>`:""}${clean(r.askAgain)?`<div class="rule ask">재질문 · ${esc(r.askAgain)}</div>`:""}`}
function liveCommon(){const m=state.mvp,req=splitReq();return`<div class="product-top"><div><div class="product-name">${esc(clean(m.name)||profile.name)}</div><div class="product-sub">${esc(clean(m.problem)||"오른쪽에서 해결할 문제를 입력하면 이 화면이 바뀝니다.")}</div></div><span class="product-badge">MY AGENT LIVE</span></div>${req.length?`<div class="req-list"><strong>필요 입력</strong> · ${req.map(esc).join(" · ")}</div>`:`<div class="empty-tip">오른쪽의 MVP 정보를 입력하면 필요한 입력과 결과 구조가 여기 표시됩니다.</div>`}`}
function liveElementary(){const m=state.mvp;return`${liveCommon()}<div class="result-shell"><small>에이전트가 만들어야 할 결과</small><strong>${esc(clean(m.outcome)||"구매 판단과 이유를 보여주는 결과")}</strong></div><div class="money-grid"><div class="metric"><small>판단 대상</small><b>${esc(clean(m.user)||"사용자 미정")}</b></div><div class="metric"><small>상태</small><b>${complete(0)?"MVP 입력 준비됨":"설계 중"}</b></div></div><div class="screen-card"><h4>지출 판단 규칙</h4><p>${esc(clean(state.refine.issue)||"MVP를 사용한 뒤 문제점을 적으면 이 영역에 반영됩니다.")}</p>${liveRules()}</div>${liveBottom()}`}
function liveSecondary(){const m=state.mvp;return`${liveCommon()}<div class="screen-card"><h4>오늘의 플랜 구조</h4><div class="study-grid"><div class="metric"><small>사용자</small><b>${esc(clean(m.user)||"학습자 미정")}</b></div><div class="metric"><small>출력 목표</small><b>${esc(clean(m.outcome)||"공부 계획 결과")}</b></div></div><div class="agenda"><div><b>01 · 우선순위 판단</b>${esc(profile.steps[0])}</div><div><b>02 · 시간 배치</b>${esc(profile.steps[1])}</div><div><b>03 · 밀린 일정 처리</b>${esc(clean(state.refine.must)||"수정 단계에서 규칙 추가")}</div></div>${liveRules()}</div>${liveBottom()}`}
function liveAdult(){const m=state.mvp;return`${liveCommon()}<div class="screen-card"><h4>여행 설계 화면</h4><div class="trip-grid"><div class="metric"><small>사용자</small><b>${esc(clean(m.user)||"여행자 미정")}</b></div><div class="metric"><small>결과</small><b>${esc(clean(m.outcome)||"일정 결과")}</b></div></div><div class="timeline"><div><span>STEP 1</span><b>${esc(profile.steps[0])}</b></div><div><span>STEP 2</span><b>${esc(profile.steps[1])}</b></div><div><span>STEP 3</span><b>${esc(profile.steps[2])}</b></div></div>${liveRules()}</div>${liveBottom()}`}
function liveBottom(){const v=state.validate;return`${state.stage>=2||clean(v.userResult)||clean(v.aiResult)?`<div class="validation"><div><small>사용자 검증</small><b>${clean(v.userResult)?"기록 있음":"대기"}</b></div><div><small>AI 검증</small><b>${clean(v.aiResult)?"기록 있음":"대기"}</b></div></div>`:""}${state.stage>=3?`<div class="arch"><small>다음 개발 방향</small><b>${arch()}</b></div>`:""}`}
function renderLive(){$("#liveState").textContent=stages[state.stage].name;$("#liveBody").innerHTML=aud==="elementary"?liveElementary():aud==="secondary"?liveSecondary():liveAdult()}
function field(label,path,value,full=false,rows=2){return`<label class="field ${full?"full":""}">${label}<textarea rows="${rows}" data-bind="${path}">${esc(value)}</textarea></label>`}
function renderForm(){let h="";if(state.stage===0){const m=state.mvp;h=`<div class="form-grid"><label class="field">에이전트 이름<input data-bind="mvp.name" value="${esc(m.name)}"></label>${field("누가 사용하나","mvp.user",m.user)}${field("어떤 문제를 해결하나","mvp.problem",m.problem,true)}${field("어떤 결과를 받아야 하나","mvp.outcome",m.outcome,true)}${field("꼭 필요한 입력","mvp.required",m.required,true)}</div>`}else if(state.stage===1){const r=state.refine;h=`<div class="form-grid">${field("써보니 가장 먼저 고칠 점","refine.issue",r.issue,true)}${field("반드시 해야 할 것","refine.must",r.must,true)}${field("절대 하지 말아야 할 것","refine.mustNot",r.mustNot,true)}${field("정보가 부족하면 다시 물어볼 조건","refine.askAgain",r.askAgain,true)}</div>`}else if(state.stage===2){const v=state.validate;h=`<div class="form-grid">${field("사용자 검증 결과","validate.userResult",v.userResult,true,4)}${field("AI 검증 결과","validate.aiResult",v.aiResult,true,4)}</div>`}else{const d=state.delivery;h=`<div class="form-grid"><label class="field">사용 위치<select data-bind="delivery.place"><option value="local" ${d.place==="local"?"selected":""}>로컬 / 채팅</option><option value="web" ${d.place==="web"?"selected":""}>웹</option></select></label><label class="field">공유 범위<select data-bind="delivery.share"><option value="personal" ${d.share==="personal"?"selected":""}>나만 사용</option><option value="small" ${d.share==="small"?"selected":""}>소수 공유</option><option value="public" ${d.share==="public"?"selected":""}>공개</option></select></label><label class="field">데이터 저장<select data-bind="delivery.data"><option value="none" ${d.data==="none"?"selected":""}>저장 불필요</option><option value="local" ${d.data==="local"?"selected":""}>브라우저/파일 저장</option><option value="database" ${d.data==="database"?"selected":""}>DB 필요</option></select></label><label class="field">외부 데이터/API<select data-bind="delivery.external"><option value="no" ${d.external==="no"?"selected":""}>불필요</option><option value="yes" ${d.external==="yes"?"selected":""}>필요</option></select></label></div>`}$("#webForm").innerHTML=h;all("[data-bind]").forEach(el=>{el.oninput=el.onchange=()=>{setPath(el.dataset.bind,el.value);save();renderLive();renderProgress();$("#aiPrompt").textContent=prompt()}})}
function setPath(path,val){const [a,b]=path.split(".");state[a][b]=val}
async function copyText(text){try{await navigator.clipboard.writeText(text);$("#saveStatus").textContent="복사됨"}catch(_){$("#saveStatus").textContent="복사 실패"}}
function render(){renderProgress();renderHeader();renderForm();renderLive();$("#aiPrompt").textContent=prompt();$("#prev").disabled=state.stage===0;$("#next").textContent=state.stage===3?"인트로로 돌아가기":"다음 단계"}
load();render();$("#copyAI").onclick=()=>copyText(prompt());$("#prev").onclick=()=>{if(state.stage>0){state.stage--;render();save()}};$("#next").onclick=()=>{if(state.stage<3){state.stage++;render();save()}else location.href="./index.html"};$("#reset").onclick=()=>{if(confirm("이 대상의 작성 기록을 초기화할까요?")){state=init();save();render()}};
})();
