const EXAMPLES = [{id:"assignment",number:"01",name:"수행평가 준비 코치",description:"마감일, 이미 한 일, 막힌 점을 정리하고 오늘 준비할 일을 정합니다.",situation:"수행평가가 5일 남았고, 자료 조사가 가장 막막하다.",sample:"과제 안내문에서 꼭 답해야 하는 질문을 세 개로 정리한다.\n오늘 30분 안에 확인할 자료 두 개의 제목과 출처를 적는다.\n자료를 읽은 뒤 내 생각 한 문장을 초안으로 쓴다."},{id:"career",number:"02",name:"진로 탐색 계획 도우미",description:"관심 분야와 확인하고 싶은 조건을 정리해 탐색 순서를 만듭니다.",situation:"디자인과 생명과학에 관심이 있지만, 어떤 활동부터 찾아봐야 할지 모르겠다.",sample:"관심이 생긴 활동을 각각 세 가지씩 적는다.\n두 분야의 직업 정보를 출처와 함께 하나씩 찾아본다.\n다음 주에 해 볼 작은 체험 또는 인터뷰 질문을 하나 고른다."},{id:"event",number:"03",name:"학교 행사 준비 에이전트",description:"행사 목표와 남은 일을 정리하고 이번 주에 할 일을 나눕니다.",situation:"반 행사가 2주 남았고, 역할과 준비물이 아직 정리되지 않았다.",sample:"행사에 꼭 필요한 결과를 한 문장으로 정한다.\n준비물을 담당자와 마감일이 보이게 목록으로 만든다.\n이번 주에 확인할 위험 요소 한 가지를 정한다."}];
const state={example:"assignment",situation:"",response:"",plan:[],tests:{}};const KEY="level2-workflow-practice-v1";const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(state));$("#saveNotice").textContent="저장했습니다. 이 브라우저에서만 보입니다."}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY))||{})}catch{}}
function selected(){return EXAMPLES.find(x=>x.id===state.example)||EXAMPLES[0]}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]))}
function renderChoices(){const root=$("#choices");root.innerHTML="";EXAMPLES.forEach(item=>{const b=document.createElement("button");b.type="button";b.className="choice"+(item.id===state.example?" selected":"");b.innerHTML=`<small>EXAMPLE ${item.number}</small><span class="check">✓</span><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p>`;b.onclick=()=>{state.example=item.id;state.situation=item.situation;state.response="";state.plan=[];renderAll();save()};root.append(b)})}
function prompt(){const e=selected();return `나는 고등학생의 ‘${e.name}’ 웹 워크플로를 만들고 있다.\n\n학생의 현재 상황: ${state.situation||e.situation}\n\n학생이 스스로 결정할 수 있도록, 오늘 할 수 있는 행동을 최대 세 개 제안해줘.\n각 행동은 한 줄씩 짧게 쓰고, 확실하지 않은 정보는 추측하지 마.\n특정 선택을 대신 결정하거나 결과를 보장하지 마.\n설명 대신 행동 제안만 출력해줘.`}
function renderPrompt(){$("#promptText").textContent=prompt()}function renderPlan(){const root=$("#planList");root.innerHTML="";state.plan.forEach((item,i)=>{const row=document.createElement("div");row.className="plan-item";row.innerHTML=`<b>${i+1}</b><span>${esc(item)}</span>`;root.append(row)});$("#previewTitle").textContent=state.plan.length?`${selected().name} · 오늘의 행동 ${state.plan.length}개`:"아직 계획을 고르는 중";$("#previewText").textContent=state.plan.length?state.plan.join(" · "):"AI의 답에서 오늘 실행할 행동을 세 개까지 골라 보세요."}
function renderAll(){renderChoices();$("#situation").value=state.situation||selected().situation;$("#aiResponse").value=state.response;renderPrompt();renderPlan();$$('[data-test]').forEach(x=>x.checked=Boolean(state.tests[x.dataset.test]))}
function setStage(n){$$('.stage').forEach(x=>x.classList.toggle('active',Number(x.dataset.stage)===n));$$('[data-step-link]').forEach(x=>x.classList.toggle('active',Number(x.dataset.stepLink)===n));window.scrollTo({top:0,behavior:"smooth"})}
async function copy(){try{await navigator.clipboard.writeText(prompt())}catch{const t=document.createElement("textarea");t.value=prompt();document.body.append(t);t.select();document.execCommand("copy");t.remove()}$("#copyPrompt").textContent="복사됨";setTimeout(()=>$("#copyPrompt").textContent="복사",1200)}
function record(){const text=`LEVEL 2 · ${selected().name}\n\n[현재 상황]\n${state.situation}\n\n[AI에 보낸 요청]\n${prompt()}\n\n[외부 AI 답]\n${state.response}\n\n[내가 고른 오늘의 행동]\n${state.plan.map((x,i)=>`${i+1}. ${x}`).join("\n")}`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download="level2-workflow-record.txt";a.click();URL.revokeObjectURL(a.href)}
load();renderAll();$$('[data-step-link]').forEach(b=>b.onclick=()=>setStage(Number(b.dataset.stepLink)));$$('[data-next]').forEach(b=>b.onclick=()=>setStage(Math.min(4,Number($('.stage.active').dataset.stage)+1)));$$('[data-prev]').forEach(b=>b.onclick=()=>setStage(Math.max(1,Number($('.stage.active').dataset.stage)-1)));$("#copyPrompt").onclick=copy;$("#situation").oninput=e=>{state.situation=e.target.value;renderPrompt();save()};$("#aiResponse").oninput=e=>{state.response=e.target.value;save()};$("#useSample").onclick=()=>{state.response=selected().sample;$("#aiResponse").value=state.response;save()};$("#makePlan").onclick=()=>{state.plan=state.response.split(/\n+/).map(x=>x.replace(/^[-•\d.\s]+/,"").trim()).filter(Boolean).slice(0,3);renderPlan();save()};$$('[data-test]').forEach(x=>x.onchange=()=>{state.tests[x.dataset.test]=x.checked;save()});$("#downloadRecord").onclick=record;
